name: epicscorelibs

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Check build from .tar
          - name: Source
            os: ubuntu-latest
            python: "3.7"
            source: true

          # Linux py builds x64

          - name: linux 3.6 amd64
            os: ubuntu-latest
            pyver: cp36-cp36m
            piparch: manylinux1_x86_64

          - name: linux 3.7 amd64
            os: ubuntu-latest
            pyver: cp37-cp37m
            piparch: manylinux1_x86_64

          - name: linux 3.8 amd64
            os: ubuntu-latest
            pyver: cp38-cp38
            piparch: manylinux1_x86_64

          - name: linux 3.9 amd64
            os: ubuntu-latest
            pyver: cp39-cp39
            piparch: manylinux2010_x86_64

         
          # Linux py builds aarch64

          - name: linux 3.6 aarch64
            os: ubuntu-latest
            pyver: cp36-cp36m
            piparch: manylinux2014_aarch64

          - name: linux 3.7 aarch64
            os: ubuntu-latest
            pyver: cp37-cp37m
            piparch: manylinux2014_aarch64

          - name: linux 3.8 aarch64
            os: ubuntu-latest
            pyver: cp38-cp38
            piparch: manylinux2014_aarch64
            
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup native python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python || '3.7' }}
          #architecture: x64

      - name: Native Prep/Info
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine
          which python
          python --version
          python -m pip --version
          python -m twine -h
          python ./gha-set-pre.py

      - name: PY Source
        run: |
          echo "PRE=$PRE"
          python -m pip install setuptools wheel nose2
          python -m pip install $PRE setuptools-dso
          python setup.py sdist --formats=gztar
          ls dist/*

      - name: PEP517 Build
        if: matrix.source
        run: |
          python -m pip wheel -v -w dist $PRE dist/*.tar.*

      - name: Native PY build
        if: matrix.python && !matrix.source
        shell: bash
        run: |
          python -m pip wheel -v -w dist --no-index --no-deps \
           --no-build-isolation --no-use-pep517 \
           --build-option --plat-name=${{ matrix.piparch }} \
           $PRE \
           dist/*.tar.*

          cd dist
          python -m pip install epicscorelibs*.whl
          python -c 'import epicscorelibs; print("IMPORT", epicscorelibs.__file__)'
          python -m nose2 -v epicscorelibs

      - name: Docker PY build
        if: matrix.pyver && !matrix.source
        run: |
          # can't use GHA native docker support since GHA magic binaries need .so absent from old manylinux images :(
          cat <<EOF > runit.sh
          #!/bin/sh
          set -e -x
          cd /io
          [ -d dist ]
          ls dist/*
          export PATH="/opt/python/${{ matrix.pyver }}/bin:\$PATH"
          which python
          python -m pip install -U pip
          python -m pip install --only-binary numpy setuptools wheel nose2 numpy
          python -m pip install $PRE setuptools-dso
          python -m pip wheel -v -w dist --no-index --no-deps \
           --no-build-isolation --no-use-pep517 \
           --build-option --plat-name=${{ matrix.piparch }} \
           $PRE \
           dist/*.tar.*

          cd dist
          python -m pip install epicscorelibs*.whl
          python -c 'import epicscorelibs; print("IMPORT", epicscorelibs.__file__)'
          python -m nose2 -v epicscorelibs

          EOF
          cat runit.sh
          chmod +x runit.sh
          docker pull quay.io/pypa/${{ matrix.piparch }}
          docker run --rm -v `pwd`:/io quay.io/pypa/${{ matrix.piparch }} ${{ matrix.pre }} /io/runit.sh

      - name: List Artifacts
        run: ls dist/*

      - name: Save Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: epicscorelibs
          path: dist/*

      - name: Upload wheels
        if: github.event_name=='push' && github.ref=='refs/heads/master' && !matrix.source
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload --skip-existing dist/epicscorelibs*.whl

      - name: Upload source
        if: github.event_name=='push' && github.ref=='refs/heads/master' && matrix.source
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload --skip-existing dist/epicscorelibs*.tar.*
